version: '3.8'

services:
  mongodb:
      image: mongo:latest
      container_name: mongodb-container
      ports:
        - "27017:27017"  # Expose MongoDB on localhost
      volumes:
        - mongodb_data:/data/db  # Persist MongoDB data
      environment:
        MONGO_INITDB_DATABASE: epl_database  # Initialize database
  kafka:
    build:
      context: .
      dockerfile: Dockerfile.kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    depends_on:
      - kafka

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master

  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile.spark-worker
    container_name: spark-worker-2
    depends_on:
      - spark-master

volumes:
  mongodb_data: